### ISSUE TITLE
Game doesn't relinquish mouse upon losing focus

### ISSUE THREAD

**Issue by wojpawlik** [StepS-/D3D9Wnd#2]
...degrading usefulness of <kbd>Alt+Tab</kbd> and <kbd>Win+Tab</kbd>. <kbd>Ctrl+G</kbd> also does nothing.
Only minimizing the game (<kbd>Shift+Esc</kbd>, <kbd>Win+D</kbd>) does relinquish mouse.

D3D9Wnd 0.7.1.1, Windows 10 1903 64-bit

<details>
<summary>Config (default)</summary>

```ini
[Misc]
EnableModule=1
StaticWindowClass=1
NoTopmost=1
SoundInBackground=1
FancyStartup=0

[FrontendSettings]
Fullscreen=0
FullscreenAlternative=0
Stretch=0
Centered=0
RunInBackground=1

[InGameSettings]
Fullscreen=0
WindowBorder=1
Stretch=0
QuickInfo=1
TopLeftPosition=0

[MultiMonitor]
Enable=0
Monitors=Max
AutoSetResolution=1
```
</details>

**Comment by StepS-** [comment]
Looks like something is causing the "Worms2D" (input) window to never be hidden, or to continue receiving input even when hidden. Unsure if I've seen this before.
I could perhaps also set it to 0x0 when unpinning, and restore otherwise.
This of course will be resolved when update 3.8 is out, since the Worms2D window is now removed there, but we still have to wait for that to happen.

**Comment by wojpawlik** [comment]
You mean, the window on the left? I see it it WormNet, but not in quick CPU play.
![obraz](https://user-images.githubusercontent.com/23058303/69884662-b7dae280-12d9-11ea-9a07-54adee144b24.png)

Can I somehow help in confirming that that is indeed the issue?

ETA?

**Comment by StepS-** [comment]
No, I was talking about in-game. The frontend is separate and not affected by this.
You should not be able to see the Worms2D window since it is merged with the main window as soon as it is created. As for why it doesn't get hidden, I'm not really sure...

**Comment by Charlyo** [comment]
Same in macos. Mouse cannot click anything. Ctrl + G does nothing

**Comment by StepS-** [comment]
D3D9Wnd is only intended for use on Windows and not with Wine or any custom window manager.

**Comment by StepS-** [comment]
I could work around this issue by doing 0x0 on the mouse input window instead of (as well as) hiding it, however 3.8 should be released pretty soon so the module will become obsolete.

**Comment by Charlyo** [comment]
are we still expecting the 3.8 update? could you add more information (ETA) ??

**Comment by StepS-** [comment]
3.8 is currently undergoing localization with target release in June.
Join the [discord server](https://discord.gg/UBRBhk6) to stay up-to-date on that.
